AWSTemplateFormatVersion: '2010-09-09'
Description: 'Basic EC2 Instance'

Parameters:
  VolumeSize:
    Type: Number
    Default: 1
    Description: Size of the docker volume storage in gb
  VolumeId:
    Type: String
    Default: ""

Resources:
  Host:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-03c4f11b50838ab5d
      InstanceType: t2.micro
      KeyName: !Ref KeyName
      BlockDeviceMappings:
        - DeviceName: /dev/xvda
          Ebs:
            VolumeType: gp3
            VolumeSize: 8
            DeleteOnTermination: true

  DataVolume:
    Type: AWS::EC2::Volume
    Condition: CreateVolume
    Properties:
      Size: !Ref VolumeSize
      VolumeType: gp3
      AvailabilityZone: !GetAtt Host.AvailabilityZone
      Tags:
        - Key: Name
          Value: Kuma-Data

  VolumeAttachment:
    Type: AWS::EC2::VolumeAttachment
    Properties:
      InstanceId: !Ref Host
      VolumeId: !If [UseExistingVolume, !Ref VolumeId, !Ref DataVolume]
      Device: /dev/sdf

Conditions:
  CreateVolume: !Equals [!Ref VolumeId, '']
  UseExistingVolume: !Not [!Equals [!Ref VolumeId, '']]